### ISSUE TITLE
"Downloads" direct link support

### ISSUE THREAD

**Issue by oathzed** [SHSharkar/Stremio-Real-Debrid-Addon#1]
Hello,

First off great addon! 

I'd like to suggest an important feature, torrents are great in the addon, but what's missing is direct download links support, these are called "Downloads" in real debrid, and you can find link on sites like rlsbb and the links are usually rapidgator that work. These are important for content like reality tv as they are released a lot faster then torrents.

Would be awesome if you can support these, thanks!

**Comment by SHSharkar** [comment]
Hello @oathzed,

Thank you for your message about adding download links. Right now, on the Stremio platform, downloaded content is being collected and shared, but it's not organized properly.

Although the content is available, it's not shown in a sorted order, which can confuse users because download items are mixed into the Movies catalog.

I will update the code to create a separate catalog for downloads, making it easier to access them.

Thanks again for your suggestion.

**Comment by SHSharkar** [comment]
@oathzed,

I do not have a dataset or dummy data to test downloads items before adding URLs to the downloads section.

It would be great if you could provide a sample dataset or sources from which I could collect data and test it locally to see what happens.

You can email me at the following temporary email address: 23d0ea02-b248-4824-bf2c-d4c26bafedba@simplelogin.com

**Comment by oathzed** [comment]
> Hello @oathzed,
> 
> Thank you for your message about adding download links. Right now, on the Stremio platform, downloaded content is being collected and shared, but it's not organized properly.
> 
> Although the content is available, it's not shown in a sorted order, which can confuse users because download items are mixed into the Movies catalog.
> 
> I will update the code to create a separate catalog for downloads, making it easier to access them.
> 
> Thanks again for your suggestion.

Thank you for considering it, yes it's important to have a separate category and display it sorted as most recently added at the start.

**Comment by oathzed** [comment]
> @oathzed,
> 
> I do not have a dataset or dummy data to test downloads items before adding URLs to the downloads section.
> 
> It would be great if you could provide a sample dataset or sources from which I could collect data and test it locally to see what happens.
> 
> You can email me at the following temporary email address: [23d0ea02-b248-4824-bf2c-d4c26bafedba@simplelogin.com](mailto:23d0ea02-b248-4824-bf2c-d4c26bafedba@simplelogin.com)

I have emailed you, thank you

**Comment by oathzed** [comment]
> > > Hello @oathzed,
> > > Thank you for your message about adding download links. Right now, on the Stremio platform, downloaded content is being collected and shared, but it's not organized properly.
> > > Although the content is available, it's not shown in a sorted order, which can confuse users because download items are mixed into the Movies catalog.
> > > I will update the code to create a separate catalog for downloads, making it easier to access them.
> > > Thanks again for your suggestion.
> > 
> > 
> > Thank you for considering it, yes it's important to have a separate category and display it sorted as most recently added at the start.
> 
> Okay, thank you so much for your feedback. I will get back to you once I have made the necessary changes. And yes, I did receive your email about the dataset for testing. Thank you so much.

I appreciate it, thank you!

**Comment by SHSharkar** [comment]
Hi There, I have released `v1.0.4` along with several new features and bug fixes. Now the Torrents downloads and Downloads folders are separate from each other and separate catalogs.

You need to uninstall and reinstall the addon again with the new version, and it will reflect the changes instantly.

**Comment by oathzed** [comment]
> Hi There, I have released `v1.0.4` along with several new features and bug fixes. Now the Torrents downloads and Downloads folders are separate from each other and separate catalogs.
> 
> You need to uninstall and reinstall the addon again with the new version, and it will reflect the changes instantly.

Thank you so much, you're awesome. I will check it out

**Comment by oathzed** [comment]
Works great, well done! Closing this issue.
