### ISSUE TITLE
Some torrent video sources don't populate in stremio

### ISSUE THREAD

**Issue by oathzed** [SHSharkar/Stremio-Real-Debrid-Addon#2]
Hello,

Some of the torrents I have in my cloud don't populate a video file to play. I've tested these same files on other apps and they populate fine.

I'll email you the magnet data 🙏

**Comment by SHSharkar** [comment]
The Stremio plugin for Real Debrid is designed to gather downloaded torrent data and files from various servers into the Downloads section. If you have magnet links, it's best to use the Real Debrid dashboard to add the torrent file or magnet link directly. Once the file is downloaded, it will appear in the Stremio catalog.

Please note that my addon wasn't created to play magnet links directly. It's not set up to work that way.

**Comment by oathzed** [comment]
> The Stremio plugin for Real Debrid is designed to gather downloaded torrent data and files from various servers into the Downloads section. If you have magnet links, it's best to use the Real Debrid dashboard to add the torrent file or magnet link directly. Once the file is downloaded, it will appear in the Stremio catalog.
> 
> Please note that my addon wasn't created to play magnet links directly. It's not set up to work that way.

Hi I think you might be miss understanding me. I'm not trying to add a magnet link, that is just a magnet link where I've downloaded the magnet torrent to real debrid and real debrid served me a download link for it, but if your addon when I go to it, it shows the name, when I click it, it goes to the next screen, but no video file is there to play, it's just empty.

I was using that magnet link as a reference so you can download it to your real debrid as well and see that it won't show in your addon.

**Comment by SHSharkar** [comment]
@oathzed ,

If the content is streamable, it will stream. Some torrents actually are not downloaded to your collection. Instead, the `Real Debrid` provides you the URL as an alias from their `Cache`.

So you might receive an empty stream URL because the `API` itself was looking for the files inside your collection.

Because most of the time `Real Debrid` shows cached data that is already downloaded to their server.

**Comment by SHSharkar** [comment]
@oathzed ,

Please install or use **v1.0.6**, which fixes the issue, and you will be able to stream the files in the `Downloads` catalog.

If in some cases it shows `Streaming not available`, you can access the `downloads` for the media, and it will be available to stream.

**Comment by oathzed** [comment]
> @oathzed ,
> 
> Please install or use **v1.0.6**, which fixes the issue, and you will be able to stream the files in the `Downloads` catalog.
> 
> If in some cases it shows `Streaming not available`, you can access the `downloads` for the media, and it will be available to stream.

Yeh I'm really not sure what's going on. I've downloaded this torrent through RD and it still doesn't show a link that's playable from your addon. It 100% cached on my cloud. And it's not like this is a one of, there's many torrents I've tried that are fully cached on RD that don't produce a link once added to my cloud
