### ISSUE TITLE
Addon link is not working

### ISSUE THREAD

**Issue by subirmazumdar** [SHSharkar/Stremio-Real-Debrid-Addon#6]
https://stremio-real-debrid-addon.devwz.com/

please check

**Comment by SHSharkar** [comment]
Hello @subirmazumdar ,

I'm really sorry about the outage. I was in the middle of moving the project to a Docker container. It was unavailable for a while. If you plan to use Docker to host this project, please follow these steps:

[docker-instructions.md](https://github.com/SHSharkar/Stremio-Real-Debrid-Addon/blob/main/docker-instructions.md)

Also, please make use of the existing endpoint without having to host it yourself.

[https://stremio-real-debrid-addon.devwz.com](https://stremio-real-debrid-addon.devwz.com/configure)

**Comment by subirmazumdar** [comment]
Thanks it working
